---
- name: Fixup kubelet client cert rotation 1/2
  lineinfile:
    path: "{{ kube_config_dir }}/kubelet.conf"
    regexp: '^    client-certificate-data: '
    line: '    client-certificate: /var/lib/kubelet/pki/kubelet-client-current.pem'
<<<<<<< HEAD
    backup: true
  notify:
    - "Control plane | reload kubelet"
=======
    backup: yes
  notify:
    - "Master | reload kubelet"
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))

- name: Fixup kubelet client cert rotation 2/2
  lineinfile:
    path: "{{ kube_config_dir }}/kubelet.conf"
    regexp: '^    client-key-data: '
    line: '    client-key: /var/lib/kubelet/pki/kubelet-client-current.pem'
<<<<<<< HEAD
    backup: true
  notify:
    - "Control plane | reload kubelet"
=======
    backup: yes
  notify:
    - "Master | reload kubelet"
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
