---
- name: Backup old certs and keys
  copy:
    src: "{{ kube_cert_dir }}/{{ item }}"
    dest: "{{ kube_cert_dir }}/{{ item }}.old"
    mode: preserve
<<<<<<< HEAD
    remote_src: true
=======
    remote_src: yes
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
  with_items:
    - apiserver.crt
    - apiserver.key
    - apiserver-kubelet-client.crt
    - apiserver-kubelet-client.key
    - front-proxy-client.crt
    - front-proxy-client.key
  ignore_errors: true  # noqa ignore-errors

- name: Backup old confs
  copy:
    src: "{{ kube_config_dir }}/{{ item }}"
    dest: "{{ kube_config_dir }}/{{ item }}.old"
    mode: preserve
<<<<<<< HEAD
    remote_src: true
=======
    remote_src: yes
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
  with_items:
    - admin.conf
    - controller-manager.conf
    - kubelet.conf
    - scheduler.conf
  ignore_errors: true  # noqa ignore-errors
