---
- name: Kubelet | reload systemd
<<<<<<< HEAD
  systemd_service:
=======
  systemd:
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
    daemon_reload: true
  listen: Node | restart kubelet

- name: Kubelet | restart kubelet
  service:
    name: kubelet
    state: restarted
  listen: Node | restart kubelet
