---
- name: Containerd | restart containerd
<<<<<<< HEAD
  systemd_service:
    name: containerd
    state: restarted
    enabled: true
    daemon-reload: true
    masked: false
=======
  systemd:
    name: containerd
    state: restarted
    enabled: yes
    daemon-reload: yes
    masked: no
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
  listen: Restart containerd

- name: Containerd | wait for containerd
  command: "{{ containerd_bin_dir }}/ctr images ls -q"
  register: containerd_ready
  retries: 8
  delay: 4
  until: containerd_ready.rc == 0
  listen: Restart containerd
