---
- name: Converge
  hosts: all
  become: true
  gather_facts: false
  roles:
    - role: bastion-ssh-config
  tasks:
    - name: Copy config to remote host
      copy:
        src: "{{ playbook_dir }}/{{ ssh_bastion_confing__name }}"
        dest: "{{ ssh_bastion_confing__name }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
<<<<<<< HEAD
        mode: "0644"
=======
        mode: 0644
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
