---
role_name_check: 1
dependency:
  name: galaxy
<<<<<<< HEAD
platforms:
  - name: bastion-01
    cloud_image: ubuntu-2004
    vm_cpu_cores: 1
    vm_memory: 512
=======
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: bastion-01
    box: generic/ubuntu2004
    cpus: 1
    memory: 512
    provider_options:
      driver: kvm
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: profile_tasks
      timeout: 120
  inventory:
    hosts:
      all:
        hosts:
        children:
          bastion:
            hosts:
              bastion-01:
<<<<<<< HEAD
  playbooks:
    create: ../../../../tests/cloud_playbooks/create-kubevirt.yml
=======
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
verifier:
  name: testinfra
