---
# TODO: Figure out why kubeadm does not fix this
- name: Set etcd-servers fact
  set_fact:
    # noqa: jinja[spacing]
    etcd_servers: >-
      {% for host in groups['etcd'] -%}
        {% if not loop.last -%}
<<<<<<< HEAD
        https://{{ hostvars[host]['main_access_ip'] | ansible.utils.ipwrap }}:2379,
        {%- endif -%}
        {%- if loop.last -%}
        https://{{ hostvars[host]['main_access_ip'] | ansible.utils.ipwrap }}:2379
=======
        https://{{ hostvars[host].access_ip | default(hostvars[host].ip | default(hostvars[host].ansible_default_ipv4['address'])) }}:2379,
        {%- endif -%}
        {%- if loop.last -%}
        https://{{ hostvars[host].access_ip | default(hostvars[host].ip | default(hostvars[host].ansible_default_ipv4['address'])) }}:2379
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
        {%- endif -%}
      {%- endfor -%}

- name: Update apiserver etcd-servers list
  replace:
    path: /etc/kubernetes/manifests/kube-apiserver.yaml
    regexp: "(etcd-servers=).*"
    replace: "\\1{{ etcd_servers }}"
