---
dependencies:
<<<<<<< HEAD
  - role: kubernetes/kubeadm_common
=======
  - role: kubernetes/tokens
    when: kube_token_auth
    tags:
      - k8s-secrets
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
  - role: adduser
    user: "{{ addusers.etcd }}"
    when:
      - etcd_deployment_type == "kubeadm"
      - not (ansible_os_family in ["Flatcar", "Flatcar Container Linux by Kinvolk", "ClearLinux"] or is_fedora_coreos)
  - role: network_plugin/calico_defaults
