---
- name: Create systemd-resolved drop-in directory
  file:
    state: directory
    name: /etc/systemd/resolved.conf.d/
<<<<<<< HEAD
    mode: "0755"
=======
    mode: 0755
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))

- name: Write Kubespray DNS settings to systemd-resolved
  template:
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf.d/kubespray.conf
    owner: root
    group: root
<<<<<<< HEAD
    mode: "0644"
=======
    mode: 0644
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
  notify: Preinstall | Restart systemd-resolved
