---
dependencies:
  - role: kubernetes-apps/external_cloud_controller/openstack
    when:
<<<<<<< HEAD
      - cloud_provider == "external"
=======
      - cloud_provider is defined
      - cloud_provider == "external"
      - external_cloud_provider is defined
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
      - external_cloud_provider == "openstack"
      - inventory_hostname == groups['kube_control_plane'][0]
    tags:
      - external-cloud-controller
      - external-openstack
  - role: kubernetes-apps/external_cloud_controller/vsphere
    when:
<<<<<<< HEAD
      - cloud_provider == "external"
=======
      - cloud_provider is defined
      - cloud_provider == "external"
      - external_cloud_provider is defined
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
      - external_cloud_provider == "vsphere"
      - inventory_hostname == groups['kube_control_plane'][0]
    tags:
      - external-cloud-controller
      - external-vsphere
  - role: kubernetes-apps/external_cloud_controller/hcloud
    when:
<<<<<<< HEAD
      - cloud_provider == "external"
=======
      - cloud_provider is defined
      - cloud_provider == "external"
      - external_cloud_provider is defined
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
      - external_cloud_provider == "hcloud"
      - inventory_hostname == groups['kube_control_plane'][0]
    tags:
      - external-cloud-controller
      - external-hcloud
  - role: kubernetes-apps/external_cloud_controller/huaweicloud
    when:
<<<<<<< HEAD
      - cloud_provider == "external"
=======
      - cloud_provider is defined
      - cloud_provider == "external"
      - external_cloud_provider is defined
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
      - external_cloud_provider == "huaweicloud"
      - inventory_hostname == groups['kube_control_plane'][0]
    tags:
      - external-cloud-controller
      - external-huaweicloud
<<<<<<< HEAD
  - role: kubernetes-apps/external_cloud_controller/oci
    when:
      - cloud_provider == "external"
      - external_cloud_provider == "oci"
      - inventory_hostname == groups['kube_control_plane'][0]
    tags:
      - external-cloud-controller
      - external-oci
=======
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
