---
role_name_check: 1
<<<<<<< HEAD
platforms:
  - name: ubuntu20
    cloud_image: ubuntu-2004
    vm_cpu_cores: 2
    vm_memory: 1024
    node_groups:
      - kube_control_plane
      - kube_node
      - k8s_cluster
  - name: almalinux9
    cloud_image: almalinux-9
    vm_cpu_cores: 2
    vm_memory: 1024
    node_groups:
      - kube_control_plane
      - kube_node
      - k8s_cluster
  - name: fedora
    cloud_image: fedora-39
    vm_cpu_cores: 2
    vm_memory: 1024
    node_groups:
      - kube_control_plane
      - kube_node
      - k8s_cluster
  - name: debian12
    cloud_image: debian-12
    vm_cpu_cores: 2
    vm_memory: 1024
    node_groups:
      - kube_control_plane
      - kube_node
      - k8s_cluster
=======
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: ubuntu20
    box: generic/ubuntu2004
    cpus: 2
    memory: 1024
    groups:
      - kube_control_plane
      - kube_node
      - k8s_cluster
    provider_options:
      driver: kvm
  - name: almalinux8
    box: almalinux/8
    cpus: 2
    memory: 1024
    groups:
      - kube_control_plane
      - kube_node
      - k8s_cluster
    provider_options:
      driver: kvm
  - name: fedora
    box: fedora/38-cloud-base
    cpus: 2
    memory: 2048
    groups:
      - kube_control_plane
      - kube_node
      - k8s_cluster
    provider_options:
      driver: kvm
  - name: debian10
    box: generic/debian10
    cpus: 2
    memory: 1024
    groups:
      - kube_control_plane
      - kube_node
      - k8s_cluster
    provider_options:
      driver: kvm
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../../../
  config_options:
    defaults:
      callbacks_enabled: profile_tasks
      timeout: 120
<<<<<<< HEAD
  playbooks:
    create: ../../../../../tests/cloud_playbooks/create-kubevirt.yml
=======
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
verifier:
  name: testinfra
