---
- name: Prepare
  hosts: all
<<<<<<< HEAD
  gather_facts: false
=======
  gather_facts: False
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
  become: true
  vars:
    ignore_assert_errors: true
  roles:
    - role: kubespray-defaults
    - role: bootstrap-os
<<<<<<< HEAD
    - role: network_facts
=======
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
    - role: kubernetes/preinstall
    - role: adduser
      user: "{{ addusers.kube }}"
  tasks:
    - name: Download CNI
      include_tasks: "../../../../download/tasks/download_file.yml"
      vars:
        download: "{{ download_defaults | combine(downloads.cni) }}"

- name: Prepare CNI
  hosts: all
<<<<<<< HEAD
  gather_facts: false
=======
  gather_facts: False
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
  become: true
  vars:
    ignore_assert_errors: true
    kube_network_plugin: cni
  roles:
    - role: kubespray-defaults
    - role: network_plugin/cni
  tasks:
    - name: Copy test container files
      copy:
        src: "{{ item }}"
        dest: "/tmp/{{ item }}"
        owner: root
<<<<<<< HEAD
        mode: "0644"
=======
        mode: 0644
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
      with_items:
        - container.json
        - sandbox.json
    - name: Create /etc/cni/net.d directory
      file:
        path: /etc/cni/net.d
        state: directory
        owner: "{{ kube_owner }}"
<<<<<<< HEAD
        mode: "0755"
=======
        mode: 0755
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
    - name: Setup CNI
      copy:
        src: "{{ item }}"
        dest: "/etc/cni/net.d/{{ item }}"
        owner: root
<<<<<<< HEAD
        mode: "0644"
=======
        mode: 0644
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
      with_items:
        - 10-mynet.conf
