---
- name: Backup etcd
  import_tasks: backup.yml

<<<<<<< HEAD
- name: Restart etcd
  systemd_service:
    name: etcd
    state: restarted
    daemon_reload: true
  when: ('etcd' in group_names)
  throttle: "{{ groups['etcd'] | length // 2 }}"
  # Etcd cluster MUST have an odd number of members
  # Truncated integer division by 2 will always return (majority - 1) which
  # means the cluster will keep quorum and stay available

- name: Restart etcd-events
  systemd_service:
    name: etcd-events
    state: restarted
    daemon_reload: true
  # TODO: this seems odd. etcd-events should be a different group possibly ?
  when: ('etcd' in group_names)
  throttle: "{{ groups['etcd'] | length // 2 }}"

- name: Wait for etcd up
  uri:
    url: "https://{% if 'etcd' in group_names %}{{ etcd_address | ansible.utils.ipwrap }}{% else %}127.0.0.1{% endif %}:2379/health"
    validate_certs: false
=======
- name: Etcd | reload systemd
  systemd:
    daemon_reload: true
  listen:
    - Restart etcd
    - Restart etcd-events

- name: Reload etcd
  service:
    name: etcd
    state: restarted
  when: is_etcd_master
  listen: Restart etcd

- name: Reload etcd-events
  service:
    name: etcd-events
    state: restarted
  when: is_etcd_master
  listen: Restart etcd-events

- name: Wait for etcd up
  uri:
    url: "https://{% if is_etcd_master %}{{ etcd_address }}{% else %}127.0.0.1{% endif %}:2379/health"
    validate_certs: no
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
    client_cert: "{{ etcd_cert_dir }}/member-{{ inventory_hostname }}.pem"
    client_key: "{{ etcd_cert_dir }}/member-{{ inventory_hostname }}-key.pem"
  register: result
  until: result.status is defined and result.status == 200
  retries: 60
  delay: 1
  listen: Restart etcd

- name: Cleanup etcd backups
  import_tasks: backup_cleanup.yml

- name: Wait for etcd-events up
  uri:
<<<<<<< HEAD
    url: "https://{% if 'etcd' in group_names %}{{ etcd_address | ansible.utils.ipwrap }}{% else %}127.0.0.1{% endif %}:2383/health"
    validate_certs: false
=======
    url: "https://{% if is_etcd_master %}{{ etcd_address }}{% else %}127.0.0.1{% endif %}:2383/health"
    validate_certs: no
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
    client_cert: "{{ etcd_cert_dir }}/member-{{ inventory_hostname }}.pem"
    client_key: "{{ etcd_cert_dir }}/member-{{ inventory_hostname }}-key.pem"
  register: result
  until: result.status is defined and result.status == 200
  retries: 60
  delay: 1
  listen: Restart etcd-events

- name: Set etcd_secret_changed
  set_fact:
    etcd_secret_changed: true
