---
- name: Disable firewalld and ufw
  when:
  - disable_service_firewall is defined and disable_service_firewall
  block:
  - name: List services
    service_facts:

  - name: Disable service firewalld
<<<<<<< HEAD
    systemd_service:
      name: firewalld
      state: stopped
      enabled: false
=======
    systemd:
      name: firewalld
      state: stopped
      enabled: no
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
    when:
      "'firewalld.service' in services and services['firewalld.service'].status != 'not-found'"

  - name: Disable service ufw
<<<<<<< HEAD
    systemd_service:
      name: ufw
      state: stopped
      enabled: false
=======
    systemd:
      name: ufw
      state: stopped
      enabled: no
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
    when:
      "'ufw.service' in services and services['ufw.service'].status != 'not-found'"
