---
helm_update: true

helm_defaults:
  atomic: true
  binary_path: "{{ bin_dir }}/helm"

helm_repository_defaults:
  binary_path: "{{ bin_dir }}/helm"
<<<<<<< HEAD
  force_update: true
=======
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
