---
- name: Check etcd certs
  include_tasks: check_certs.yml
  when: cert_management == "script"
  tags:
    - etcd-secrets
    - facts

- name: Generate etcd certs
  include_tasks: "gen_certs_script.yml"
  when:
<<<<<<< HEAD
    - cert_management == "script"
=======
    - cert_management | d('script') == "script"
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
  tags:
    - etcd-secrets

- name: Trust etcd CA
  include_tasks: upd_ca_trust.yml
  when:
<<<<<<< HEAD
    - ('etcd' in group_names) or ('kube_control_plane' in group_names)
=======
    - inventory_hostname in groups['etcd'] | union(groups['kube_control_plane']) | unique | sort
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
  tags:
    - etcd-secrets

- name: Trust etcd CA on nodes if needed
  include_tasks: upd_ca_trust.yml
  when:
<<<<<<< HEAD
    - kube_network_plugin in ["calico", "flannel", "cilium"] or cilium_deploy_additionally
    - kube_network_plugin != "calico" or calico_datastore == "etcd"
    - ('k8s_cluster' in group_names)
=======
    - kube_network_plugin in ["calico", "flannel", "cilium"] or cilium_deploy_additionally | default(false) | bool
    - kube_network_plugin != "calico" or calico_datastore == "etcd"
    - inventory_hostname in groups['k8s_cluster']
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
  tags:
    - etcd-secrets

- name: "Gen_certs | Get etcd certificate serials"
  command: "openssl x509 -in {{ etcd_cert_dir }}/node-{{ inventory_hostname }}.pem -noout -serial"
  register: "etcd_client_cert_serial_result"
  changed_when: false
<<<<<<< HEAD
  check_mode: false
  when:
    - kube_network_plugin in ["calico", "flannel", "cilium"] or cilium_deploy_additionally
    - kube_network_plugin != "calico" or calico_datastore == "etcd"
    - ('k8s_cluster' in group_names)
  tags:
    - master    # master tag is deprecated and replaced by control-plane
    - control-plane
=======
  check_mode: no
  when:
    - kube_network_plugin in ["calico", "flannel", "cilium"] or cilium_deploy_additionally | default(false) | bool
    - kube_network_plugin != "calico" or calico_datastore == "etcd"
    - inventory_hostname in groups['k8s_cluster']
  tags:
    - master
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
    - network

- name: Set etcd_client_cert_serial
  set_fact:
    etcd_client_cert_serial: "{{ etcd_client_cert_serial_result.stdout.split('=')[1] }}"
  when:
<<<<<<< HEAD
    - kube_network_plugin in ["calico", "flannel", "cilium"] or cilium_deploy_additionally
    - kube_network_plugin != "calico" or calico_datastore == "etcd"
    - ('k8s_cluster' in group_names)
  tags:
    - master    # master tag is deprecated and replaced by control-plane
    - control-plane
=======
    - kube_network_plugin in ["calico", "flannel", "cilium"] or cilium_deploy_additionally | default(false) | bool
    - kube_network_plugin != "calico" or calico_datastore == "etcd"
    - inventory_hostname in groups['k8s_cluster']
  tags:
    - master
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
    - network

- name: Install etcdctl and etcdutl binary
  import_role:
    name: etcdctl_etcdutl
  tags:
    - etcdctl
    - etcdutl
    - upgrade
  when:
<<<<<<< HEAD
    - ('etcd' in group_names)
=======
    - inventory_hostname in groups['etcd']
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
    - etcd_cluster_setup

- name: Install etcd
  include_tasks: "install_{{ etcd_deployment_type }}.yml"
<<<<<<< HEAD
  when: ('etcd' in group_names)
=======
  when: is_etcd_master
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
  tags:
    - upgrade

- name: Configure etcd
  include_tasks: configure.yml
<<<<<<< HEAD
  when: ('etcd' in group_names)

- name: Refresh etcd config
  include_tasks: refresh_config.yml
  when: ('etcd' in group_names)
=======
  when: is_etcd_master

- name: Refresh etcd config
  include_tasks: refresh_config.yml
  when: is_etcd_master
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))

- name: Restart etcd if certs changed
  command: /bin/true
  notify: Restart etcd
<<<<<<< HEAD
  when:
    - ('etcd' in group_names)
    - etcd_cluster_setup
    - etcd_secret_changed | default(false)
=======
  when: is_etcd_master and etcd_cluster_setup and etcd_secret_changed | default(false)
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))

- name: Restart etcd-events if certs changed
  command: /bin/true
  notify: Restart etcd
<<<<<<< HEAD
  when:
    - ('etcd' in group_names)
    - etcd_events_cluster_setup
    - etcd_secret_changed | default(false)
=======
  when: is_etcd_master and etcd_events_cluster_setup and etcd_secret_changed | default(false)
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))

# After etcd cluster is assembled, make sure that
# initial state of the cluster is in `existing`
# state instead of `new`.
- name: Refresh etcd config again for idempotency
  include_tasks: refresh_config.yml
<<<<<<< HEAD
  when: ('etcd' in group_names)
=======
  when: is_etcd_master
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
