---
- name: Refresh config | Create etcd config file
  template:
    src: etcd.env.j2
    dest: /etc/etcd.env
<<<<<<< HEAD
    mode: "0640"
  notify: Restart etcd
  when:
    - ('etcd' in group_names)
    - etcd_cluster_setup
=======
    mode: 0640
  notify: Restart etcd
  when: is_etcd_master and etcd_cluster_setup
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))

- name: Refresh config | Create etcd-events config file
  template:
    src: etcd-events.env.j2
    dest: /etc/etcd-events.env
<<<<<<< HEAD
    mode: "0640"
  notify: Restart etcd-events
  when:
    - ('etcd' in group_names)
    - etcd_events_cluster_setup
=======
    mode: 0640
  notify: Restart etcd-events
  when: is_etcd_master and etcd_events_cluster_setup
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
