---
- name: Kubernetes Persistent Volumes | Copy GCP PD CSI Storage Class template
  template:
    src: "gcp-pd-csi-storage-class.yml.j2"
    dest: "{{ kube_config_dir }}/gcp-pd-csi-storage-class.yml"
<<<<<<< HEAD
    mode: "0644"
=======
    mode: 0644
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
  register: manifests
  when:
    - inventory_hostname == groups['kube_control_plane'][0]

- name: Kubernetes Persistent Volumes | Add GCP PD CSI Storage Class
  kube:
    name: gcp-pd-csi
    kubectl: "{{ bin_dir }}/kubectl"
    resource: StorageClass
    filename: "{{ kube_config_dir }}/gcp-pd-csi-storage-class.yml"
    state: "latest"
  when:
    - inventory_hostname == groups['kube_control_plane'][0]
    - manifests.changed
