---
- name: Kubernetes Persistent Volumes | Copy Azure CSI Storage Class template
  template:
    src: "azure-csi-storage-class.yml.j2"
    dest: "{{ kube_config_dir }}/azure-csi-storage-class.yml"
<<<<<<< HEAD
    mode: "0644"
=======
    mode: 0644
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
  register: manifests
  when:
    - inventory_hostname == groups['kube_control_plane'][0]

- name: Kubernetes Persistent Volumes | Add Azure CSI Storage Class
  kube:
    name: azure-csi
    kubectl: "{{ bin_dir }}/kubectl"
    resource: StorageClass
    filename: "{{ kube_config_dir }}/azure-csi-storage-class.yml"
    state: "latest"
  when:
    - inventory_hostname == groups['kube_control_plane'][0]
    - manifests.changed
