---
- name: Youki | Download youki
  include_tasks: "../../../download/tasks/download_file.yml"
  vars:
    download: "{{ download_defaults | combine(downloads.youki) }}"

- name: Youki | Copy youki binary from download dir
  copy:
<<<<<<< HEAD
    src: "{{ local_release_dir }}/youki"
    dest: "{{ youki_bin_dir }}/youki"
    mode: "0755"
=======
    src: "{{ local_release_dir }}/youki_{{ youki_version | regex_replace('\\.', '_') }}_linux/youki-{{ youki_version }}/youki"
    dest: "{{ youki_bin_dir }}/youki"
    mode: 0755
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
    remote_src: true
