---
# include to workaround mitogen issue
# https://github.com/dw/mitogen/issues/663

- name: Cinder CSI Driver | Write cacert file
  copy:
    src: "{{ cinder_cacert }}"
    dest: "{{ kube_config_dir }}/cinder-cacert.pem"
    group: "{{ kube_cert_group }}"
<<<<<<< HEAD
    mode: "0640"
=======
    mode: 0640
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
  delegate_to: "{{ delegate_host_to_write_cacert }}"
