---
- name: Haproxy | Cleanup potentially deployed nginx-proxy
  file:
    path: "{{ kube_manifest_dir }}/nginx-proxy.yml"
    state: absent

- name: Haproxy | Make haproxy directory
  file:
    path: "{{ haproxy_config_dir }}"
    state: directory
<<<<<<< HEAD
    mode: "0755"
=======
    mode: 0755
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
    owner: root

- name: Haproxy | Write haproxy configuration
  template:
    src: "loadbalancer/haproxy.cfg.j2"
    dest: "{{ haproxy_config_dir }}/haproxy.cfg"
    owner: root
<<<<<<< HEAD
    mode: "0755"
    backup: true
=======
    mode: 0755
    backup: yes
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))

- name: Haproxy | Get checksum from config
  stat:
    path: "{{ haproxy_config_dir }}/haproxy.cfg"
<<<<<<< HEAD
    get_attributes: false
    get_checksum: true
    get_mime: false
=======
    get_attributes: no
    get_checksum: yes
    get_mime: no
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
  register: haproxy_stat

- name: Haproxy | Write static pod
  template:
    src: manifests/haproxy.manifest.j2
    dest: "{{ kube_manifest_dir }}/haproxy.yml"
<<<<<<< HEAD
    mode: "0640"
=======
    mode: 0640
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
