---
- name: Kube-router | Add annotations on kube_control_plane
  command: "{{ kubectl }} annotate --overwrite node {{ ansible_hostname }} {{ item }}"
  with_items:
  - "{{ kube_router_annotations_master }}"
  delegate_to: "{{ groups['kube_control_plane'][0] }}"
<<<<<<< HEAD
  when: kube_router_annotations_master is defined and 'kube_control_plane' in group_names
=======
  when: kube_router_annotations_master is defined and inventory_hostname in groups['kube_control_plane']
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))

- name: Kube-router | Add annotations on kube_node
  command: "{{ kubectl }} annotate --overwrite node {{ ansible_hostname }} {{ item }}"
  with_items:
  - "{{ kube_router_annotations_node }}"
  delegate_to: "{{ groups['kube_control_plane'][0] }}"
<<<<<<< HEAD
  when: kube_router_annotations_node is defined and 'kube_node' in group_names
=======
  when: kube_router_annotations_node is defined and inventory_hostname in groups['kube_node']
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))

- name: Kube-router | Add common annotations on all servers
  command: "{{ kubectl }} annotate --overwrite node {{ ansible_hostname }} {{ item }}"
  with_items:
  - "{{ kube_router_annotations_all }}"
  delegate_to: "{{ groups['kube_control_plane'][0] }}"
<<<<<<< HEAD
  when: kube_router_annotations_all is defined and 'k8s_cluster' in group_names
=======
  when: kube_router_annotations_all is defined and inventory_hostname in groups['k8s_cluster']
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
