---

- name: Query Azure VMs
  command: azure vm list-ip-address --json {{ azure_resource_group }}
  register: vm_list_cmd

- name: Set vm_list
  set_fact:
    vm_list: "{{ vm_list_cmd.stdout }}"

- name: Generate inventory
  template:
    src: inventory.j2
    dest: "{{ playbook_dir }}/inventory"
<<<<<<< HEAD
    mode: "0644"
=======
    mode: 0644
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
