---
- name: Kubernetes Snapshots | Copy Cinder CSI Snapshot Class template
  template:
    src: "cinder-csi-snapshot-class.yml.j2"
    dest: "{{ kube_config_dir }}/cinder-csi-snapshot-class.yml"
<<<<<<< HEAD
    mode: "0644"
=======
    mode: 0644
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
  register: manifests
  when:
    - inventory_hostname == groups['kube_control_plane'][0]

- name: Kubernetes Snapshots | Add Cinder CSI Snapshot Class
  kube:
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ kube_config_dir }}/cinder-csi-snapshot-class.yml"
    state: "latest"
  when:
    - inventory_hostname == groups['kube_control_plane'][0]
    - manifests.changed
