---
role_name_check: 1
<<<<<<< HEAD
platforms:
  - name: almalinux9
    cloud_image: almalinux-9
    vm_cpu_cores: 1
    vm_memory: 1024
    node_groups:
      - kube_control_plane
  - name: ubuntu20
    cloud_image: ubuntu-2004
    vm_cpu_cores: 1
    vm_memory: 1024
    node_groups:
      - kube_control_plane
=======
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: almalinux8
    box: almalinux/8
    cpus: 1
    memory: 1024
    nested: true
    groups:
      - kube_control_plane
    provider_options:
      driver: kvm
  - name: ubuntu20
    box: generic/ubuntu2004
    cpus: 1
    memory: 1024
    nested: true
    groups:
      - kube_control_plane
    provider_options:
      driver: kvm
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../../../
  config_options:
    defaults:
      callbacks_enabled: profile_tasks
      timeout: 120
  inventory:
    group_vars:
      all:
        become: true
<<<<<<< HEAD
  playbooks:
    create: ../../../../../tests/cloud_playbooks/create-kubevirt.yml
=======
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
verifier:
  name: testinfra
