---
metallb_enabled: false
metallb_log_level: info
metallb_port: "7472"
metallb_memberlist_port: "7946"
metallb_speaker_enabled: "{{ metallb_enabled }}"
metallb_speaker_nodeselector:
  kubernetes.io/os: "linux"
metallb_controller_nodeselector:
  kubernetes.io/os: "linux"
metallb_speaker_tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Exists
metallb_controller_tolerations: []
<<<<<<< HEAD
metallb_loadbalancer_class: ""
=======
metallb_loadbalancer_class: ""
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
