---
- name: Check ansible version
  import_playbook: ansible_version.yml

<<<<<<< HEAD
# These are inventory compatibility tasks with two purposes:
# - to ensure we keep compatibility with old style group names
# - to reduce inventory boilerplate (defining parent groups / empty groups)

- name: Define groups for legacy less structured inventories
  hosts: all
  gather_facts: false
  tags: always
  tasks:
    - name: Match needed groups by their old names or definition
      vars:
        group_mappings:
          kube_control_plane:
            - kube-master
          kube_node:
            - kube-node
          calico_rr:
            - calico-rr
          no_floating:
            - no-floating
          k8s_cluster:
            - kube_node
            - kube_control_plane
            - calico_rr
      group_by:
        key: "{{ (group_names | intersect(item.value) | length > 0) | ternary(item.key, '_all') }}"
      loop: "{{ group_mappings | dict2items }}"

- name: Check inventory settings
  hosts: all
  gather_facts: false
  tags: always
  roles:
    - validate_inventory

- name: Install bastion ssh config
  hosts: bastion[0]
  gather_facts: false
=======
# These are inventory compatibility tasks to ensure we keep compatibility with old style group names

- name: Add kube-master nodes to kube_control_plane
  hosts: kube-master
  gather_facts: false
  tags: always
  tasks:
    - name: Add nodes to kube_control_plane group
      group_by:
        key: 'kube_control_plane'

- name: Add kube-node nodes to kube_node
  hosts: kube-node
  gather_facts: false
  tags: always
  tasks:
    - name: Add nodes to kube_node group
      group_by:
        key: 'kube_node'

- name: Add k8s-cluster nodes to k8s_cluster
  hosts: k8s-cluster
  gather_facts: false
  tags: always
  tasks:
    - name: Add nodes to k8s_cluster group
      group_by:
        key: 'k8s_cluster'

- name: Add calico-rr nodes to calico_rr
  hosts: calico-rr
  gather_facts: false
  tags: always
  tasks:
    - name: Add nodes to calico_rr group
      group_by:
        key: 'calico_rr'

- name: Add no-floating nodes to no_floating
  hosts: no-floating
  gather_facts: false
  tags: always
  tasks:
    - name: Add nodes to no-floating group
      group_by:
        key: 'no_floating'

- name: Install bastion ssh config
  hosts: bastion[0]
  gather_facts: False
>>>>>>> 2cb8c8544 (Fix logical error when checking for boostrap-os (#10867) (#10953))
  environment: "{{ proxy_disable_env }}"
  roles:
    - { role: kubespray-defaults }
    - { role: bastion-ssh-config, tags: ["localhost", "bastion"] }
